const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');

exports.run = async ({ window, openFiles, documents, samplePdf, app, recovery, diagnostics }) => {
  const output = path.join(path.resolve(process.env.QINGYE_SMOKE_ROOT||process.env.PORTABLE_EXECUTABLE_DIR||process.cwd()), 'test-output');
  await fs.mkdir(output, { recursive: true });
  const errors = [];
  window.webContents.on('console-message', (_event, ...args) => {
    const details = typeof args[0] === 'object' ? args[0] : { level: args[0], message: args[1] };
    if (details.level === 'error' || details.level === 3) errors.push(details.message);
    console.log('RENDERER:', details.message);
  });
  const run = source => window.webContents.executeJavaScript(source, true);
  const timeout = promise => Promise.race([promise, new Promise((_, reject) => setTimeout(() => reject(new Error('Integration test timed out')), 60000))]);
  await run('new Promise(resolve => setTimeout(resolve, 600))');
  await fs.writeFile(path.join(output, 'home.png'), (await window.webContents.capturePage()).toPNG());
  const first = path.join(output, 'first.pdf'), second = path.join(output, 'second.pdf');
  await fs.writeFile(first, samplePdf('First reader'));
  await fs.writeFile(second, samplePdf('Second reader'));
  const opened = await openFiles([first, second]);
  // Pass data explicitly; this tests the same document-open path used by the native picker.
  await timeout(run(`qingye.addDocuments(${JSON.stringify(opened.map(d => ({ ...d, state: {}, bytes: Array.from(d.bytes) })))})`));
  await require('./design-smoke.cjs').run(window,output);
  if(process.argv.includes('--design-only')) { diagnostics.success(); app.exit(0); return; }
  const result = await timeout(run(`(async () => {
    const s = [...qingye.sessions.values()];
    const a = s[0].app, b = s[1].app;
    const outline = await a.pdfDocument.getOutline();
    const page = await a.pdfDocument.getPage(1);
    const text = (await page.getTextContent()).items.map(i => i.str).join(' ');
    const annotations = await page.getAnnotations();
    a.pdfViewer.currentPageNumber = 2; b.pdfViewer.currentPageNumber = 1;
    qingye.activate(s[0].id);
    a.eventBus.dispatch('find', { source: window, type: '', query: 'reader', phraseSearch: true, caseSensitive: false, entireWord: false, highlightAll: true, findPrevious: false });
    await new Promise(resolve => setTimeout(resolve, 1200));
    return { tabs: s.length, pages: a.pagesCount, outline: outline.map(x => x.title), text, annotations: annotations.map(x => x.subtype), firstPage: a.pdfViewer.currentPageNumber, secondPage: b.pdfViewer.currentPageNumber, matches: a.findController.pageMatches.reduce((n,x) => n+(x?.length || 0),0), sandboxed: typeof require === 'undefined', language: a.l10n.getLanguage() };
  })()`));
  assert.equal(result.tabs, 2); assert.equal(result.pages, 2);
  assert.deepEqual(result.outline, ['Getting started', 'Chapter 2']);
  assert.match(result.text, /First reader/); assert.ok(result.annotations.includes('Highlight'));
  assert.ok(result.matches >= 1); assert.equal(result.secondPage, 1); assert.equal(result.sandboxed, true);
  const original = await fs.readFile(first);
  const viewModes = await timeout(run(`(async () => {
    const [s, second] = [...qingye.sessions.values()]; qingye.activate(s.id);
    const v = qingye.views, viewer = s.app.pdfViewer;
    document.getElementById('viewButton').click();
    document.querySelector('[data-layout="double"]').click();
    await new Promise(resolve => setTimeout(resolve,150));
    const double = viewer.spreadMode;
    await v.change('cover',true); const cover = viewer.spreadMode;
    await v.change('vertical',false); const paged = viewer.scrollMode;
    await v.change('vertical',true); const vertical = viewer.scrollMode;
    await v.change('color','night');
    const night = s.frame.contentWindow.getComputedStyle(viewer.getPageView(0).div).filter;
    await v.change('color','sepia');
    const sepia = s.frame.contentWindow.getComputedStyle(viewer.getPageView(0).div).filter;
    await v.change('color','gray');
    const gray = s.frame.contentWindow.getComputedStyle(viewer.getPageView(0).div).filter;
    await v.change('crop',[5,6,7,8]);
    const crop = s.frame.contentWindow.getComputedStyle(viewer.getPageView(0).div).clipPath;
    let invalidCrop = false;
    try { await v.change('crop',[80,0,0,0]); } catch { invalidCrop = true; }
    const rotation = viewer.pagesRotation;
    await v.change('rotate'); const rotated = viewer.pagesRotation === (rotation+90)%360;
    await v.change('thumbnails'); const thumbs = !document.getElementById('navigationPanel').hidden && document.querySelector('[data-nav="thumbnails"]').getAttribute('aria-pressed') === 'true' && !s.frame.contentDocument.getElementById('outerContainer').classList.contains('viewsManagerOpen') ? 1 : 0; qingye.navigation.close();
    viewer.currentPageNumber = 2;
    await new Promise(resolve => setTimeout(resolve,250));
    await v.change('reflow',true);
    const reflow = !s.reflowPanel.hidden && s.reflowText.textContent.includes('Chapter 2');
    s.reflowPrev.click(); await new Promise(resolve => setTimeout(resolve,400));
    const reflowPrevious = s.reflowText.textContent.includes('First reader');
    s.reflowNext.click(); await new Promise(resolve => setTimeout(resolve,400));
    const reflowNext = s.reflowText.textContent.includes('Chapter 2');
    const slider = s.reflowPanel.querySelector('input'); slider.value = 28; slider.dispatchEvent(new Event('input'));
    const fontSize = s.view.fontSize;
    await v.change('reflow',false);
    const isolated = second.app.pdfViewer.spreadMode === 0 && second.view.color === 'light';
    qingye.syncDirty(s); const clean = !s.dirty;
    await qingye.saveSession(s,false);
    await v.change('crop',[0,0,0,0]); await v.change('color','light');
    await v.change('layout','single'); viewer.pagesRotation = 0; viewer.currentPageNumber = 1;
    document.getElementById('viewPanel').hidePopover();
    return { double,cover,paged,vertical,night,sepia,gray,crop,invalidCrop,rotated,thumbs,reflow,reflowPrevious,reflowNext,fontSize,isolated,clean };
  })()`));
  console.log('VIEW MODES', JSON.stringify(viewModes));
  assert.equal(viewModes.double,1); assert.equal(viewModes.cover,2); assert.equal(viewModes.paged,3); assert.equal(viewModes.vertical,0);
  assert.match(viewModes.night,/invert/); assert.match(viewModes.sepia,/sepia/); assert.match(viewModes.gray,/grayscale/);
  assert.match(viewModes.crop,/5% 6% 7% 8%/);
  for (const flag of ['invalidCrop','rotated','reflow','reflowPrevious','reflowNext','isolated','clean']) assert.equal(viewModes[flag],true,flag);
  assert.equal(viewModes.thumbs,1); assert.equal(viewModes.fontSize,28);
  assert.deepEqual(await fs.readFile(first),original,'View settings must not change saved PDF bytes');
  const expandedFeatures = await timeout(run(`(async () => {
    const [s,other]=[...qingye.sessions.values()];qingye.activate(s.id);
    await qingye.views.change('color','tone-3');
    const preset=s.view.paper==='#093448'&&s.view.ink==='#b5c9d0';
    const mapping=s.frame.contentDocument.querySelector('#qingye-reading-color feComponentTransfer').childElementCount===3;
    await qingye.views.change('custom-color',{paper:'#073e12',ink:'#edf7e9'});
    const custom=s.view.color==='custom';await qingye.views.change('color','light');
    await qingye.navigation.show('search');
    const query=document.getElementById('searchQuery');query.value='reader';query.dispatchEvent(new Event('input',{bubbles:true}));
    await new Promise(resolve=>setTimeout(resolve,900));
    const searchResults=document.querySelectorAll('#navigationContent .navigationRow').length;
    const searchCount=s.app.findController.pageMatches.reduce((n,x)=>n+(x?.length||0),0);
    await qingye.navigation.search(s,'READER',{caseSensitive:true});await new Promise(resolve=>setTimeout(resolve,350));
    const caseSensitive=s.app.findController.pageMatches.every(x=>!x.length);
    await qingye.navigation.search(s,'reader');await new Promise(resolve=>setTimeout(resolve,350));
    await qingye.navigation.show('outline');
    const outlineRows=document.querySelectorAll('#navigationContent .outlineTitle').length;
    const filter=document.querySelector('#navigationControls input');filter.value='Chapter 2';filter.dispatchEvent(new Event('input'));
    const filtered=document.querySelectorAll('#navigationContent .outlineTitle').length;
    await qingye.navigation.show('thumbnails');
    const thumbnailCards=document.querySelectorAll('.thumbnailCard').length;
    await qingye.navigation.show('bookmarks');document.querySelector('#navigationControls button').click();
    const bookmark=s.bookmarks.length===1;
    qingye.navigation.close();await qingye.compare(s.id,other.id);
    s.app.pdfViewer.currentPageNumber=2;await new Promise(resolve=>setTimeout(resolve,300));
    const sideBySide=!s.panel.hidden&&!other.panel.hidden&&s.panel.classList.contains('compareLeft')&&other.panel.classList.contains('compareRight');
    const syncPage=other.app.pdfViewer.currentPageNumber===s.app.pdfViewer.currentPageNumber;
    document.getElementById('endCompare').click();s.app.pdfViewer.currentPageNumber=1;
    await qingye.tools.open('stamp');
    const preview=document.getElementById('toolCanvas').width>0;
    document.getElementById('toolText').value='UI stamp test';
    await qingye.tools.execute();const toolExecuted=document.getElementById('toolProgress').textContent.includes('已生成结果');
    await qingye.tools.open('export');document.getElementById('toolFormat').value='txt';document.getElementById('toolBatch').checked=true;
    await qingye.tools.execute();const batch=document.getElementById('toolProgress').textContent.includes('first-export.txt')&&document.getElementById('toolProgress').textContent.includes('second-export.txt');
    document.getElementById('closeTools').click();
    const bytes=await qingye.tools.snapshot(s);
    const inspect=await desktop.toolsJob(s.id,bytes,{action:'inspect'});
    const text=await desktop.toolsJob(s.id,bytes,{action:'stamp',pages:'1',text:'Verified offline stamp 中文印章',rect:[.1,.55,.8,.7],size:18});
    const task=s.frame.contentWindow.pdfjsLib.getDocument({data:new Uint8Array(text.bytes)});const pdf=await task.promise;
    const stampText=(await(await pdf.getPage(1)).getTextContent()).items.map(x=>x.str).join('');
    const stamped=stampText.includes('Verified offline stamp')&&stampText.includes('中文印章');await task.destroy();
    const office=await desktop.toolsJob(s.id,bytes,{action:'export',format:'docx'});
    const zipOffice=office.bytes[0]===80&&office.bytes[1]===75&&office.extension==='.docx';
    const encrypted=await desktop.toolsJob(s.id,bytes,{action:'encrypt',userPassword:'test-reader',ownerPassword:'test-owner',copy:false});
    const locked=s.frame.contentWindow.pdfjsLib.getDocument({data:new Uint8Array(encrypted.bytes),password:'test-reader'});const protectedDoc=await locked.promise;
    const aesRead=protectedDoc.numPages===2;await locked.destroy();
    qingye.syncDirty(s);
    return {preset,mapping,custom,searchResults,searchCount,caseSensitive,outlineRows,filtered,thumbnailCards,bookmark,sideBySide,syncPage,preview,toolExecuted,batch,inspectPages:inspect.data.pages,stamped,zipOffice,aesRead,originalClean:!s.dirty};
  })()`));
  console.log('EXPANDED FEATURES',JSON.stringify(expandedFeatures));
  for(const flag of ['preset','mapping','custom','caseSensitive','bookmark','sideBySide','syncPage','preview','toolExecuted','batch','stamped','zipOffice','aesRead','originalClean'])assert.equal(expandedFeatures[flag],true,flag);
  assert.ok(expandedFeatures.searchResults>0);assert.ok(expandedFeatures.searchCount>0);assert.equal(expandedFeatures.outlineRows,2);assert.equal(expandedFeatures.filtered,1);assert.equal(expandedFeatures.thumbnailCards,2);assert.equal(expandedFeatures.inspectPages,2);
  await run(`(async () => {
    const s = [...qingye.sessions.values()][1]; qingye.activate(s.id);
    await qingye.views.change('layout','double'); await qingye.views.change('cover',true);
    await qingye.views.change('vertical',false); await qingye.views.change('color','sepia');
    await qingye.views.change('crop',[3,4,5,6]); await qingye.views.change('reflow',true);
    s.view.fontSize = 26; await qingye.closeTab(s.id);
  })()`);
  const reopened = await openFiles([second]);
  await timeout(run(`qingye.addDocuments(${JSON.stringify(reopened.map(d => ({...d,bytes:Array.from(d.bytes)})))})`));
  const restoredView = await run('qingye.viewState([...qingye.sessions.values()][1])');
  assert.equal(restoredView.spreadMode,2); assert.equal(restoredView.scrollMode,3); assert.equal(restoredView.color,'sepia');
  assert.deepEqual(restoredView.crop,[3,4,5,6]); assert.equal(restoredView.reflow,true); assert.equal(restoredView.fontSize,26);
  await run('qingye.activate([...qingye.sessions.keys()][0])');
  // Native fullscreen is asynchronous; verify both entry and the Escape exit path.
  await run("qingye.views.change('fullscreen')");
  await new Promise(resolve => setTimeout(resolve,350)); assert.equal(window.isFullScreen(),true);
  await run("document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
  await new Promise(resolve => setTimeout(resolve,350)); assert.equal(window.isFullScreen(),false);
  // Create a real FreeText editor via PDF.js's editor layer, then save through native IPC.
  const editingPromise = timeout(run(`(async () => {
    const s = [...qingye.sessions.values()][0]; const a = s.app;
    a.pdfViewer.currentPageNumber = 1;
    await a.pdfViewer.pagesPromise;
    a.eventBus.dispatch('switchannotationeditormode', { source: window, mode: 3 });
    await new Promise(resolve => setTimeout(resolve, 500));
    const layer = a.pdfViewer.getPageView(0).annotationEditorLayer.annotationEditorLayer;
    const rect = layer.div.getBoundingClientRect();
    layer.div.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, button: 0, pointerId: 1, clientX: rect.left+120, clientY: rect.top+240 }));
    layer.div.dispatchEvent(new PointerEvent('pointerup', { bubbles: true, button: 0, pointerId: 1, clientX: rect.left+120, clientY: rect.top+240 }));
    await new Promise(resolve => setTimeout(resolve, 200));
    const editor = s.frame.contentDocument.querySelector('.freeTextEditor .internal');
    if (!editor) throw new Error('FreeText editor was not created');
    editor.textContent = 'Saved by Qingye PDF';
    editor.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText', data: 'Saved by Qingye PDF' }));
    await qingye.checkpoint();const draftFocused=s.frame.contentDocument.activeElement===editor;
    await new Promise(resolve=>{qingye.resumeDraftTest=resolve;});
    qingye.commit(s); qingye.syncDirty(s);
    const dirty = s.dirty;
    const saved = await qingye.saveSession(s, false);
    const bytes = await a.pdfDocument.saveDocument();
    const loading = s.frame.contentWindow.pdfjsLib.getDocument({data:bytes});
    const reopened = await loading.promise;
    const annots = await (await reopened.getPage(1)).getAnnotations();
    const text = annots.filter(x=>x.subtype==='FreeText').map(x=>x.contentsObj?.str || x.contents || '');
    await loading.destroy();
    return { dirty, saved, draftFocused,clean: !s.dirty, text, types: annots.map(x=>x.subtype) };
  })()`));
  for(let attempt=0;attempt<100&&!await run('!!qingye.resumeDraftTest');attempt++)await new Promise(resolve=>setTimeout(resolve,100));
  const draftEntry=recovery.entries.find(e=>e.dirty&&e.draft);assert.ok(draftEntry,'Uncommitted text must produce a draft');
  const liveDraft=Array.from(await fs.readFile(path.join(recovery.folder,draftEntry.draft)));
  const backedUp=await run(`(async()=>{const child=[...qingye.sessions.values()][0].frame.contentWindow;const task=child.pdfjsLib.getDocument({data:new Uint8Array(${JSON.stringify(liveDraft)})});const doc=await task.promise;const yes=(await(await doc.getPage(1)).getAnnotations()).some(a=>a.contentsObj?.str?.includes('Saved by Qingye PDF'));await task.destroy();return yes;})()`);
  assert.equal(backedUp,true,'Draft must contain the live text before explicit save');await run('qingye.resumeDraftTest()');const editing=await editingPromise;
  console.log('EDITING RESULT', JSON.stringify(editing));
  assert.equal(editing.dirty, true); assert.equal(editing.saved, true); assert.equal(editing.clean, true);
  assert.equal(editing.draftFocused,true,'Draft backup must restore the active text editor');
  assert.ok(editing.types.includes('FreeText')); assert.ok(editing.text.some(t => t.includes('Saved by Qingye PDF')));
  const disk = Array.from(await fs.readFile(first));
  const persisted = await run(`(async () => {
    const s = [...qingye.sessions.values()][0];
    const loading = s.frame.contentWindow.pdfjsLib.getDocument({ data: new Uint8Array(${JSON.stringify(disk)}) });
    const doc = await loading.promise;
    const annots = await (await doc.getPage(1)).getAnnotations();
    const text = annots.filter(x => x.subtype === 'FreeText').map(x => x.contentsObj?.str || x.contents || '');
    await loading.destroy(); return text;
  })()`);
  assert.ok(persisted.some(t => t.includes('Saved by Qingye PDF')));
  const drawings = await timeout(run(`(async () => {
    const s = [...qingye.sessions.values()][0]; const a = s.app;
    const child = s.frame.contentWindow;
    const layer = a.pdfViewer.getPageView(0).annotationEditorLayer.annotationEditorLayer;
    const stroke = async (mode, y) => {
      a.eventBus.dispatch('switchannotationeditormode', {source:window, mode});
      await new Promise(resolve => setTimeout(resolve, 150));
      const rect = layer.div.getBoundingClientRect();
      const event = (type,x,yy) => new child.PointerEvent(type,{bubbles:true,button:0,buttons:type==='pointerup'?0:1,pointerId:11,pointerType:'mouse',isPrimary:true,clientX:rect.left+x,clientY:rect.top+yy});
      layer.div.dispatchEvent(event('pointerdown',180,y));
      for(let x=190;x<=310;x+=10) layer.div.dispatchEvent(event('pointermove',x,y+Math.sin(x/20)*8));
      layer.div.dispatchEvent(event('pointerup',310,y));
      a.pdfViewer._layerProperties.annotationEditorUIManager.endCurrentEditing();
      await new Promise(resolve => setTimeout(resolve,100));
    };
    await stroke(15,340);
    await stroke(9,390);
    const textNode = [...s.frame.contentDocument.querySelectorAll('.textLayer span')].find(node => node.textContent.includes('First reader'));
    if (!textNode) throw new Error('Text selection layer was not rendered');
    const range = s.frame.contentDocument.createRange(); range.selectNodeContents(textNode.firstChild);
    const selection = child.getSelection(); selection.removeAllRanges(); selection.addRange(range);
    a.pdfViewer._layerProperties.annotationEditorUIManager.highlightSelection('main_toolbar');
    await new Promise(resolve => setTimeout(resolve,200));
    qingye.commit(s); qingye.syncDirty(s);
    const dirty = s.dirty;
    await qingye.saveSession(s,false);
    return { dirty, storageSize:a.pdfDocument.annotationStorage.size };
  })()`));
  console.log('DRAWINGS', JSON.stringify(drawings));
  assert.equal(drawings.dirty, true);
  const drawingDisk = Array.from(await fs.readFile(first));
  const drawingTypes = await run(`(async () => {
    const child = [...qingye.sessions.values()][0].frame.contentWindow;
    const task = child.pdfjsLib.getDocument({data:new Uint8Array(${JSON.stringify(drawingDisk)})});
    const doc = await task.promise; const annots = await (await doc.getPage(1)).getAnnotations();
    const types=annots.map(a=>a.subtype); await task.destroy(); return types;
  })()`);
  console.log('DRAWING TYPES', JSON.stringify(drawingTypes));
  assert.ok(drawingTypes.includes('Ink'));
  assert.ok(drawingTypes.filter(t=>t==='Highlight').length >= 2);
  await timeout(run(`(async () => {
    const second = [...qingye.sessions.values()][1]; qingye.activate(second.id); await qingye.closeTab(second.id);
    qingye.activate([...qingye.sessions.keys()][0]);
    await new Promise(resolve => setTimeout(resolve, 1200));
  })()`));
  assert.equal(await run('[...qingye.sessions.values()][0].dirty'), false, 'View resizing must not dirty a saved document');
  await fs.writeFile(path.join(output, 'reader.png'), (await window.webContents.capturePage()).toPNG());
  assert.equal(await run('qingye.sessions.size'), 1);
  await run("document.getElementById('viewButton').click()");
  await new Promise(resolve => setTimeout(resolve,250));
  await fs.writeFile(path.join(output, 'view-modes.png'), (await window.webContents.capturePage()).toPNG());
  await run("document.getElementById('viewPanel').hidePopover(); qingye.views.change('reflow',true)");
  await new Promise(resolve => setTimeout(resolve,250));
  await fs.writeFile(path.join(output, 'reflow.png'), (await window.webContents.capturePage()).toPNG());
  await run("qingye.views.change('reflow',false); qingye.navigation.show('search')");
  await new Promise(resolve=>setTimeout(resolve,350));
  const navigationEdits=await run(`(()=>{const s=[...qingye.sessions.values()][0];qingye.syncDirty(s);return{dirty:s.dirty,saved:JSON.parse(s.savedHash),now:[...(s.app.pdfDocument.annotationStorage.serializable.map||[])]};})()`);
  assert.equal(navigationEdits.dirty,false,'Opening navigation must not alter saved annotations');
  const inkChangeDetection=await run(`(()=>{const s=[...qingye.sessions.values()][0];const before=JSON.parse(s.savedHash);const changed=JSON.parse(s.savedHash);const ink=changed.find(([,value])=>value.annotationType===15)[1];ink.paths.points[0][0]+=10;const moved=!qingye.sameEdits(JSON.stringify(before),JSON.stringify(changed));ink.paths.points[0][0]-=10;ink.thickness+=1;const thickness=!qingye.sameEdits(JSON.stringify(before),JSON.stringify(changed));return{moved,thickness};})()`);
  assert.equal(inkChangeDetection.moved,true);assert.equal(inkChangeDetection.thickness,true);
  await fs.writeFile(path.join(output,'search.png'),(await window.webContents.capturePage()).toPNG());
  await run("qingye.navigation.show('outline')");await new Promise(resolve=>setTimeout(resolve,250));
  await fs.writeFile(path.join(output,'outline.png'),(await window.webContents.capturePage()).toPNG());
  await run("qingye.navigation.close(); qingye.tools.open('text')");await new Promise(resolve=>setTimeout(resolve,250));
  await fs.writeFile(path.join(output,'toolbox.png'),(await window.webContents.capturePage()).toPNG());
  const usability=await timeout(run(`(async()=>{
    document.getElementById('closeTools').click();const s=[...qingye.sessions.values()][0];
    await qingye.navigation.show('search');await qingye.navigation.search(s,'reader');await new Promise(resolve=>setTimeout(resolve,500));
    const context=document.querySelector('.searchMatch mark')?.textContent.toLowerCase()==='reader';
    const rows=[...document.querySelectorAll('.searchMatch')];rows.at(-1).click();await new Promise(resolve=>setTimeout(resolve,250));const selected=s.app.findController.selected.pageIdx===Number(rows.at(-1).dataset.page)-1&&s.app.findController.selected.matchIdx===Number(rows.at(-1).dataset.match);
    await qingye.navigation.show('comments');const notes=s.notes;
    const md=await desktop.exportNotes(s.id,notes,'md',await qingye.tools.snapshot(s));const word=await desktop.exportNotes(s.id,notes,'docx',await qingye.tools.snapshot(s));
    const noteExport=new TextDecoder().decode(new Uint8Array(md.bytes)).includes('Saved by Qingye PDF')&&word.bytes[0]===80&&word.bytes[1]===75;
    await qingye.navigation.show('thumbnails');s.pageOrganizer.move(2,1);const reorder=await s.pageOrganizer.apply('reorder');
    const task=s.frame.contentWindow.pdfjsLib.getDocument({data:new Uint8Array(reorder.bytes)});const doc=await task.promise;const first=(await(await doc.getPage(1)).getTextContent()).items.map(x=>x.str).join('');await task.destroy();
    await qingye.tools.open('outline');const editor=qingye.tools.outlineEditor;editor.set([[1,'Root',1],[2,'Child',2],[1,'Final',2]]);editor.move(2,0);const tree=editor.get().map(r=>r[1]).join(',')==='Final,Root,Child';
    await qingye.tools.execute();const written=await desktop.toolsJob(s.id,await qingye.tools.snapshot(s),{action:'outline',toc:editor.get()});const outlined=s.frame.contentWindow.pdfjsLib.getDocument({data:new Uint8Array(written.bytes)});const pdf=await outlined.promise;const outline=(await pdf.getOutline())[0].title==='Final';await outlined.destroy();
    const headings=await desktop.toolsJob(s.id,await qingye.tools.snapshot(s),{action:'inspect',headings:true});
    const stamp=await desktop.stampLibrary('add',{kind:'stamp',name:'Test date',text:'2026-09-27',size:18,color:'#123456',opacity:1});const saved=await desktop.stampLibrary('load',stamp.id);await desktop.stampLibrary('remove',stamp.id);
    document.getElementById('closeTools').click();await qingye.checkpoint();
    return {context,selected,noteExport,notes:notes.length,reordered:first.includes('Chapter 2'),tree,outline,autoOutline:headings.data.headings.length>0,stampLibrary:saved.settings.text==='2026-09-27'};
  })()`));
  for(const flag of ['context','selected','noteExport','reordered','tree','outline','autoOutline','stampLibrary'])assert.equal(usability[flag],true,flag);
  await run("qingye.tools.open('outline')");await new Promise(resolve=>setTimeout(resolve,250));
  await fs.writeFile(path.join(output,'outline-editor.png'),(await window.webContents.capturePage()).toPNG());
  await run("document.getElementById('closeTools').click(); qingye.navigation.show('comments')");await new Promise(resolve=>setTimeout(resolve,400));
  await fs.writeFile(path.join(output,'notes.png'),(await window.webContents.capturePage()).toPNG());
  await run('qingye.navigation.close()');
  const colorFile=path.join(output,'color-image.pdf');await fs.writeFile(colorFile,samplePdf('Color image reader',true));
  const colorOpened=await openFiles([colorFile]);await timeout(run(`qingye.addDocuments(${JSON.stringify(colorOpened.map(d=>({...d,state:{},bytes:Array.from(d.bytes)})))})`));
  const imageMode=await timeout(run(`(async()=>{const s=[...qingye.sessions.values()].at(-1);await new Promise(resolve=>setTimeout(resolve,400));await qingye.views.change('color','tone-3');await qingye.views.change('preserve-images',true);await qingye.views.change('brightness',.9);const overlay=s.frame.contentDocument.querySelector('.originalImageOverlay');const viewport=s.app.pdfViewer.getPageView(0).viewport;const r=s.imageRects[0][0];const box=[...viewport.convertToViewportPoint(r[0],r[1]),...viewport.convertToViewportPoint(r[2],r[3])];const sx=overlay.width/s.app.pdfViewer.getPageView(0).viewport.width,sy=overlay.height/s.app.pdfViewer.getPageView(0).viewport.height;const pixel=Array.from(overlay.getContext('2d').getImageData((box[0]+box[2])/2*sx,(box[1]+box[3])/2*sy,1,1).data);s.frame.contentDocument.getElementById('viewerContainer').scrollTop=250;await new Promise(resolve=>setTimeout(resolve,350));const layerRect=overlay.getBoundingClientRect(),frameRect=s.frame.getBoundingClientRect();const point={x:Math.round(frameRect.left+layerRect.left+(box[0]+box[2])/2/viewport.width*layerRect.width),y:Math.round(frameRect.top+layerRect.top+(box[1]+box[3])/2/viewport.height*layerRect.height)};return {pixel,preserve:qingye.viewState(s).preserveImages,brightness:s.view.brightness,point,filter:s.frame.contentWindow.getComputedStyle(overlay.closest('.page')).filter};})()`));
  assert.deepEqual(imageMode.pixel,[255,0,0,255]);assert.equal(imageMode.filter,'none');const visiblePixel=(await window.webContents.capturePage({...imageMode.point,width:1,height:1})).toBitmap();assert.deepEqual(Array.from(visiblePixel.subarray(0,4)),[0,0,255,255],'Original image color must be visible in the compositor');assert.equal(imageMode.preserve,true);assert.equal(imageMode.brightness,.9);
  await fs.writeFile(path.join(output,'preserve-images.png'),(await window.webContents.capturePage()).toPNG());
  await run('qingye.closeTab([...qingye.sessions.keys()].at(-1)); qingye.activate([...qingye.sessions.keys()][0])');
  const resolvedFirst=await fs.realpath(first);const record=[...documents.values()].find(r=>r.path===resolvedFirst);
  const draftBytes=await run(`(async()=>{const s=[...qingye.sessions.values()][0];return Array.from(await qingye.tools.snapshot(s));})()`);
  const {Recovery}=require('../recovery.cjs');const crashed=new Recovery(recovery.folder,99999999);
  await crashed.checkpoint([{id:record.id,name:record.name,path:record.path,hash:record.hash,state:{page:2},dirty:true,bytes:new Uint8Array(draftBytes)}],record.id);
  const recovered=await timeout(run(`(async()=>{const list=await desktop.recoveryList();const item=list.find(i=>i.drafts>0);const opened=await desktop.restoreSession(item.token);await qingye.addDocuments(opened);const s=[...qingye.sessions.values()].at(-1);qingye.syncDirty(s);const values={dirty:s.dirty,detached:s.path===null,page:s.app.pdfViewer.currentPageNumber,text:(await(await s.app.pdfDocument.getPage(1)).getAnnotations()).some(a=>a.contentsObj?.str?.includes('Saved by Qingye PDF'))};s.recovered=false;qingye.syncDirty(s);await qingye.closeTab(s.id);return values;})()`));
  assert.equal(recovered.dirty,true);assert.equal(recovered.detached,true);assert.equal(recovered.page,2);assert.equal(recovered.text,true);
  const large=await timeout(run(`(async()=>{const s=[...qingye.sessions.values()][0];const r=await desktop.toolsJob(s.id,await qingye.tools.snapshot(s),{action:'organize',mode:'reorder',pages:Array(250).fill('1,2').join(',')});return Array.from(r.bytes);})()`));
  const largeFile=path.join(output,'large-500-pages.pdf');await fs.writeFile(largeFile,new Uint8Array(large));
  const largeOpened=await openFiles([largeFile]);const started=Date.now();
  await timeout(run(`qingye.addDocuments(${JSON.stringify(largeOpened.map(d=>({...d,state:{},bytes:Array.from(d.bytes)})))})`));
  const largeOpenMs=Date.now()-started;
  const performance=await timeout(run(`(async()=>{const s=[...qingye.sessions.values()].at(-1);s.app.pdfViewer.scrollMode=3;s.app.pdfViewer.currentPageNumber=500;await new Promise(resolve=>setTimeout(resolve,600));await qingye.navigation.show('thumbnails');await new Promise(resolve=>setTimeout(resolve,300));const values={pages:s.app.pagesCount,lastPage:s.app.pdfViewer.currentPageNumber,renderedThumbnails:[...document.querySelectorAll('.thumbnailCard canvas')].filter(c=>c.closest('[data-rendered]')).length};qingye.navigation.close();await qingye.closeTab(s.id);return values;})()`));
  assert.equal(performance.pages,500);assert.equal(performance.lastPage,500);assert.ok(performance.renderedThumbnails<50);performance.openMs=largeOpenMs;
  const pageEditing=await require('./editing-smoke.cjs').run(window,output);
  await fs.writeFile(path.join(output, 'integration-result.json'), JSON.stringify({ runId:diagnostics.runId,pageEditing,result, viewModes, expandedFeatures, usability,imageMode,recovered,performance,restoredView, fullscreen:true, editing, persisted, drawings, drawingTypes, errors }, null, 2));
  if (errors.some(e => /Uncaught|Refused to|Failed to load module/i.test(e))) throw new Error(errors.join('\n'));
  console.log('INTEGRATION PASS', JSON.stringify({ result, editing, drawings, drawingTypes }));
  diagnostics.success();
  app.exit(0);
};
