const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('desktop', {
  appVersion: () => ipcRenderer.invoke('app-version'),
  platform: process.platform,
  titleBarTheme: dark => ipcRenderer.invoke('title-bar-theme', !!dark),
  windowState: () => ipcRenderer.invoke('window-state'),
  // Window style (0.9.2): read once, synchronously, so the first frame is drawn in the right style.
  windowStyle: (() => { try { return ipcRenderer.sendSync('window-style-sync'); } catch { return null; } })(),
  setWindowStyle: value => ipcRenderer.invoke('set-window-style', value),
  windowControl: action => ipcRenderer.invoke('window-control', String(action)),
  relaunchOnClose: value => ipcRenderer.invoke('relaunch-on-close', !!value),
  open: () => ipcRenderer.invoke('open'),
  recent: () => ipcRenderer.invoke('recent'),
  openRecent: id => ipcRenderer.invoke('open-recent', id),
  example: () => ipcRenderer.invoke('example'),
  save: (id, data, saveAs, embedFonts, password) => ipcRenderer.invoke('save', id, data, saveAs, embedFonts, password),
  closeChoice: name => ipcRenderer.invoke('close-choice', name),
  confirmDiscardEdit: name => ipcRenderer.invoke('confirm-discard-edit',name),
  closeDocument: (id, state) => ipcRenderer.invoke('close-document', id, state),
  remember: (id, state) => ipcRenderer.invoke('remember', id, state),
  fullscreen: () => ipcRenderer.invoke('fullscreen'),
  exitFullscreen: () => ipcRenderer.invoke('exit-fullscreen'),
  pickAsset: kind => ipcRenderer.invoke('pick-asset', kind),
  stampLibrary: (action,value) => ipcRenderer.invoke('stamp-library',action,value),
  batchFolder: () => ipcRenderer.invoke('batch-folder'),
  toolsJob: (id,bytes,request) => ipcRenderer.invoke('tools-job',id,bytes,request),
  newWindow: id => ipcRenderer.invoke('new-window',id),
  cancelJob: id => ipcRenderer.invoke('cancel-job',id),
  onJobProgress: callback => {const listener=(_event,id,data)=>callback(id,data);ipcRenderer.on('job-progress',listener);return()=>ipcRenderer.removeListener('job-progress',listener);},
  checkpoint: (items,activeId) => ipcRenderer.invoke('checkpoint',items,activeId),
  recoveryList: () => ipcRenderer.invoke('recovery-list'),
  restoreSession: token => ipcRenderer.invoke('restore-session',token),
  lastSessionCount: () => ipcRenderer.invoke('last-session-count'),
  recentRemove: id => ipcRenderer.invoke('recent-remove',id),
  recentClear: () => ipcRenderer.invoke('recent-clear'),
  openDataFolder: () => ipcRenderer.invoke('open-data-folder'),
  setLanguage: (code, explicit) => ipcRenderer.invoke('set-language',code,!!explicit),
  assocStatus: () => ipcRenderer.invoke('assoc-status'),
  assocRegister: kinds => ipcRenderer.invoke('assoc-register',kinds),
  assocUnregister: () => ipcRenderer.invoke('assoc-unregister'),
  assocChoose: kind => ipcRenderer.invoke('assoc-choose',kind),
  assocOpenSettings: () => ipcRenderer.invoke('assoc-open-settings'),
  discardRecovery: token => ipcRenderer.invoke('discard-recovery',token),
  finishSession: (items,activeId) => ipcRenderer.invoke('finish-session',items,activeId),
  exportNotes: (id,notes,format,bytes) => ipcRenderer.invoke('export-notes',id,notes,format,bytes),
  dropped: files => ipcRenderer.invoke('drop', files.map(file => webUtils.getPathForFile(file))),
  newMarkdown: () => ipcRenderer.invoke('markdown-new'),
  markdownExample: () => ipcRenderer.invoke('markdown-example'),
  saveMarkdown: (id, text, saveAs) => ipcRenderer.invoke('save-markdown', id, text, saveAs),
  reloadMarkdown: id => ipcRenderer.invoke('markdown-reload', id),
  checkMarkdown: () => ipcRenderer.invoke('markdown-check'),
  markdownAsset: (id, source) => ipcRenderer.invoke('markdown-asset', id, source),
  markdownOpenLink: (id, href) => ipcRenderer.invoke('markdown-open-link', id, href),
  markdownSaveImage: (id, bytes, extension) => ipcRenderer.invoke('markdown-save-image', id, bytes, extension),
  markdownPickImage: id => ipcRenderer.invoke('markdown-pick-image', id),
  markdownImagePaths: (id, files) => ipcRenderer.invoke('markdown-image-paths', id, files.map(file => webUtils.getPathForFile(file))),
  mdOpenFolder: fromDocument => ipcRenderer.invoke('markdown-open-folder', fromDocument || null),
  mdTree: dir => ipcRenderer.invoke('markdown-tree', dir),
  mdOpenPath: file => ipcRenderer.invoke('markdown-open-path', file),
  mdFileOp: (target, op, arg) => ipcRenderer.invoke('markdown-file-op', target, op, arg),
  mdSetEol: (id, eol) => ipcRenderer.invoke('markdown-set-eol', id, eol),
  mdReopenEncoding: (id, encoding) => ipcRenderer.invoke('markdown-reopen-encoding', id, encoding),
  mdExportSave: (id, ext, data, title) => ipcRenderer.invoke('markdown-export-save', id, ext, data, title),
  mdExportPdf: (id, html, options) => ipcRenderer.invoke('markdown-export-pdf', id, html, options),
  mdExportImage: (id, html, options) => ipcRenderer.invoke('markdown-export-image', id, html, options),
  mdPandocInfo: custom => ipcRenderer.invoke('markdown-pandoc-info', custom),
  mdPandocExport: (id, format, text, custom) => ipcRenderer.invoke('markdown-pandoc-export', id, format, text, custom),
  mdPandocImport: custom => ipcRenderer.invoke('markdown-pandoc-import', custom),
  aiState: () => ipcRenderer.invoke('ai-state'),
  aiUpsert: input => ipcRenderer.invoke('ai-upsert', input),
  aiRemove: id => ipcRenderer.invoke('ai-remove', id),
  aiDefaults: values => ipcRenderer.invoke('ai-defaults', values),
  aiPrompts: prompts => ipcRenderer.invoke('ai-prompts', prompts),
  aiModels: id => ipcRenderer.invoke('ai-models', id),
  aiChat: (jobId, request) => ipcRenderer.invoke('ai-chat', jobId, request),
  aiCancel: jobId => ipcRenderer.invoke('ai-cancel', jobId),
  aiImportText: text => ipcRenderer.invoke('ai-import-text', text),
  aiImportFile: () => ipcRenderer.invoke('ai-import-file'),
  aiExport: includeKeys => ipcRenderer.invoke('ai-export', includeKeys),
  aiServer: values => ipcRenderer.invoke('ai-server', values),
  aiBridgeReply: (id, ok, value) => ipcRenderer.invoke('ai-bridge-reply', id, ok, value),
  onAiEvent: callback => { const listener = (_event, id, data) => callback(id, data); ipcRenderer.on('ai-event', listener); return () => ipcRenderer.removeListener('ai-event', listener); },
  onAiBridge: callback => { const listener = (_event, id, name, args, meta) => callback(id, name, args, meta); ipcRenderer.on('ai-bridge', listener); return () => ipcRenderer.removeListener('ai-bridge', listener); },
  converterInfo: () => ipcRenderer.invoke('converter-info'),
  notesMarkdown: (id,notes) => ipcRenderer.invoke('notes-markdown',id,notes),
  converterPresets: () => ipcRenderer.invoke('converter-presets'),
  converterSavePreset: value => ipcRenderer.invoke('converter-save-preset',value),
  converterDeletePreset: id => ipcRenderer.invoke('converter-delete-preset',id),
  converterExtensions: format => ipcRenderer.invoke('converter-extensions', format),
  converterPickInputs: () => ipcRenderer.invoke('converter-pick-inputs'),
  converterPickOutput: (format, first) => ipcRenderer.invoke('converter-pick-output', format, first),
  converterPickDirectory: () => ipcRenderer.invoke('converter-pick-directory'),
  converterPickOption: flag => ipcRenderer.invoke('converter-pick-option', flag),
  converterRun: config => ipcRenderer.invoke('converter-run', config),
  converterCancel: job => ipcRenderer.invoke('converter-cancel', job),
  converterReveal: token => ipcRenderer.invoke('converter-reveal', token),
  mdHistory: id => ipcRenderer.invoke('markdown-history', id),
  mdHistoryRead: (id, name) => ipcRenderer.invoke('markdown-history-read', id, name),
  mdThemes: () => ipcRenderer.invoke('markdown-themes'),
  mdThemeRead: id => ipcRenderer.invoke('markdown-theme-read', id),
  mdThemeImport: () => ipcRenderer.invoke('markdown-theme-import'),
  mdThemeFolder: () => ipcRenderer.invoke('markdown-theme-folder'),
  mdKatexCss: () => ipcRenderer.invoke('markdown-katex-css'),
  mdImageSave: (id, bytes, ext, options) => ipcRenderer.invoke('markdown-image-save', id, bytes, ext, options),
  mdImageImport: (id, files, options) => ipcRenderer.invoke('markdown-image-import', id, files, options),
  mdImageImportFiles: (id, files, options) => ipcRenderer.invoke('markdown-image-import', id, files.map(f => webUtils.getPathForFile(f)), options),
  mdPickImageFiles: id => ipcRenderer.invoke('markdown-pick-image-files', id),
  mdCopyImages: (id, text, options) => ipcRenderer.invoke('markdown-copy-images', id, text, options),
  mdImageOp: (id, source, op) => ipcRenderer.invoke('markdown-image-op', id, source, op),
  alwaysOnTop: flag => ipcRenderer.invoke('always-on-top', flag),
  spellReplace: word => ipcRenderer.invoke('spell-replace', word),
  spellLearn: word => ipcRenderer.invoke('spell-learn', word),
  editCommand: command => ipcRenderer.invoke('edit-command', command),
  libraryStatus: () => ipcRenderer.invoke('library-status'),
  libraryRead: id => ipcRenderer.invoke('library-read', id),
  libraryPut: (id, pages, note) => ipcRenderer.invoke('library-put', id, pages, note),
  librarySearch: query => ipcRenderer.invoke('library-search', query),
  libraryClear: () => ipcRenderer.invoke('library-clear'),
  citationLookup: doi => ipcRenderer.invoke('citation-lookup', doi),
  saveTextFile: (name, text) => ipcRenderer.invoke('save-text-file', name, text),
  ready: () => ipcRenderer.send('ready'),
  finishClose: () => ipcRenderer.send('finish-close'),
  onCommand: callback => {
    const listener = (_event, command, data) => callback(command, data);
    ipcRenderer.on('command', listener);
    return () => ipcRenderer.removeListener('command', listener);
  },
});
