const fs = require('node:fs'); const path = require('node:path'); const crypto = require('node:crypto'); const root = path.resolve(__dirname, '..');
const update = (name, change) => { const file = path.join(root, name); fs.writeFileSync(file, change(fs.readFileSync(file, 'utf8'))); };
update('README.md', text => text.replace('0.9.0（源码交付，exe 由构建方按 HANDOFF 生成）', '0.9.0（Windows x64 便携版）').replace('没有 0.8.2 Setup 安装包', '没有 0.9.0 Setup 安装包').replace('## 使用\n', '## 文档转换（0.9.0）\n\n首页“文档转换”或标题栏“转换”打开文档转换中心。内置官方 Pandoc 3.12，无需用户单独安装；直接提供原版 51 个输入 / 76 个输出格式入口、模板、Defaults、引用排版和 Lua 过滤器。PDF 默认可选青页内置排版，无需 TeX；Pandoc 外部 PDF 引擎仍需对应程序。详情见 [CONVERSION.md](CONVERSION.md)。\n\n独立重写引擎的旧路线已停止，本版复用原版引擎。原有 PDF 阅读、编辑、OCR 和 Markdown 工作流保留。\n\n## 使用\n'));
update('FEATURES.md', text => text.replace('# 青页 PDF 0.8.2 功能范围', '# 青页 PDF 0.9.0 功能范围').replace('0.8.2 以源码交付，构建后得到', '0.9.0 提供').replace('## ', '## ').replace('0.8.2 新增设置面板', '0.8.2 已有设置面板').replace('本次没有同版本安装包。', '本次没有同版本安装包。\n\n0.9.0 新增文档转换中心，随包提供未修改的官方 Pandoc 3.12 引擎。51 / 76 个格式入口直接来自引擎，支持引用、模板、Defaults 和 Lua；内置 PDF 排版与外部 PDF 引擎分开选择。具体参数、安全保护、资源行为与验证范围见 [CONVERSION.md](CONVERSION.md)。').replace(/需安装 Pandoc/g, '使用内置 Pandoc').replace(/需要 Pandoc/g, '使用内置 Pandoc'));
update('CHANGELOG.md', text => '# 0.9.0 · 内置 Pandoc 与文档转换中心\n\n- 开发路线改为直接复用官方 Pandoc 3.12 引擎；不使用此前独立转换原型。\n- 首页与标题栏增加文档转换中心，动态读取 51 个输入与 76 个输出格式入口。\n- 增加目录、章节编号、CSL 引用、模板、Defaults、Lua 与附加参数入口；分章节 HTML 导出目录 ZIP。\n- 原 Markdown 导入 / 导出优先使用随包引擎，不需安装系统 Pandoc。\n- PDF 可选择青页内置 Chromium 排版或 Pandoc 外部引擎，后者保留原版依赖要求。\n- 输出先转换后原子保存；错误、取消与外部修改不覆盖已有文件，并保护输入及已打开文档。\n- 提供 Pandoc 版权与源码快照，新增界面语言同步到四套翻译。\n\n' + text);
fs.writeFileSync(path.join(root, 'HANDOFF.md'), '# 青页 PDF 0.9.0 构建说明\n\n本次交付 Windows x64 便携 EXE、青页源码与依赖源码包。用户无需安装 Node.js、Python、Pandoc。外部 PDF 引擎、JSON 过滤器等自定义工具仍遵循原版依赖要求。\n\n从源码重建需要 Node.js 22+；冻结 PDF 后端需要 Python 3.12 和 backend/requirements.txt 中的依赖。开发环境先运行 npm ci，再运行 scripts/prepare-pandoc.ps1 校验并准备官方引擎。如源码包不含 backend/bin，运行 npm run build:backend。已有完整工作目录可复用已冻结的后端。\n\n验证：npm test、npm run smoke:conversion、npm run smoke、npm run smoke:markdown、npm run safety。测试输出可以用 QINGYE_SMOKE_ROOT 指定独立目录；部分原生窗口能力需使用正常窗口模式，不能用 offscreen 代替。\n\n构建：npm run dist；源码归档：python scripts/package-source.py；交付：node scripts/prepare-delivery.cjs 目标目录。源码包不包含已编译的 Pandoc.exe，prepare-pandoc.ps1 下载固定官方发布包并校验已保存的 SHA-256。\n\n若修改 Pandoc 本身，解开依赖源码包中的 pandoc-3.12-source.tar.gz，按上游 INSTALL.md / Cabal 构建文件准备 Haskell 工具链；本次并未重新编译或修改该引擎。保留原许可、版权、变更记录并更新版本 / 来源清单。\n\n产品范围见 CONVERSION.md 与 FEATURES.md；实际测试和包校验见交付的 BUILD-REPORT.md / SHA256-0.9.0.json。\n');
const file = path.join(root, 'third-party-source/pandoc-3.12-source.tar.gz'), index = path.join(root, 'third-party-source/sources.json'), sources = JSON.parse(fs.readFileSync(index));
sources.push({ name: 'pandoc', version: '3.12', commit: '381230ee36d8fa871c28f8982e22579f1a8f723b', file: path.basename(file), sha256: crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'), url: 'https://github.com/jgm/pandoc/tree/3.12', contents: 'Complete tracked repository snapshot including CLI, Lua engine, server, data and upstream build files' });
fs.writeFileSync(index, JSON.stringify(sources, null, 2) + '\n');
